[package]
name = "vercanard"
version = "1.0.0"
entrypoint = "template.typ"
authors = [ "Ana Gelez <https://ana.gelez.xyz>" ]
license = "GPL-3.0"
description = "A colorful CV template"
repository = "https://github.com/elegaanz/vercanard"
categories = [ "cv" ]
keywords = [ "CV", "Resume", "Color" ]
exclude = [ "*.pdf" ]

[template]
path = "."
entrypoint = "template.typ"
thumbnail = "thumbnail.png"
