name: Test PR
on:
  pull_request: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Extract package names and versions from changed files
        id: extract-package
        uses: actions/github-script@v7
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const packages = new Set();
            files.forEach(file => {
              const match = file.filename.match(/^packages\/preview\/([^\/]+)\/([^\/]+)\//);
              if (match) {
                packages.add({ namespace: "preview", name: match[1], version: match[2] });
              }
            });

            let sparseCheckoutPaths;
            if (packages.size === 0) {
              sparseCheckoutPaths = "packages/";
            } else {
              sparseCheckoutPaths = Array.from(packages).map((pkg) => `packages/preview/${pkg.name}/${pkg.version}/`).join('\n');
            }
            core.setOutput('sparse-checkout-paths', sparseCheckoutPaths);

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ steps.extract-package.outputs.sparse-checkout-paths }}
            bundler/
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: bundler

      - name: Build bundler
        run: cargo build --release --manifest-path bundler/Cargo.toml

      - name: Test packaging
        run: bundler/target/release/bundler
      - uses: actions/checkout@v4
      - uses: typst/package-check@v1
        with:
        installation-id: ${{ secrets.GITHUB_INSTALLATION_ID }}
        app-id: ${{ secrets.GITHUB_APP_ID }}
        private-key: ${{ secrets.GITHUB_PRIVATE_KEY }}